// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKM5iKMZiw-oa3H3LeiE14qonrtinVUzs',
    appId: '1:805237617586:web:a4be8e9509f35518702aab',
    messagingSenderId: '805237617586',
    projectId: 'untitled20-3ecfc',
    authDomain: 'untitled20-3ecfc.firebaseapp.com',
    storageBucket: 'untitled20-3ecfc.firebasestorage.app',
    measurementId: 'G-XC3TW9JL18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzNnZ_qpf34zHDnOb6Hj-FpZSX8Y5RsDc',
    appId: '1:805237617586:android:fd734d54947c8650702aab',
    messagingSenderId: '805237617586',
    projectId: 'untitled20-3ecfc',
    storageBucket: 'untitled20-3ecfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRB9loUsan_-Xlpcq4Q5pfDI_b5mupqfs',
    appId: '1:805237617586:ios:5529ed810d885dfe702aab',
    messagingSenderId: '805237617586',
    projectId: 'untitled20-3ecfc',
    storageBucket: 'untitled20-3ecfc.firebasestorage.app',
    iosBundleId: 'com.example.untitled20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRB9loUsan_-Xlpcq4Q5pfDI_b5mupqfs',
    appId: '1:805237617586:ios:5529ed810d885dfe702aab',
    messagingSenderId: '805237617586',
    projectId: 'untitled20-3ecfc',
    storageBucket: 'untitled20-3ecfc.firebasestorage.app',
    iosBundleId: 'com.example.untitled20',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKM5iKMZiw-oa3H3LeiE14qonrtinVUzs',
    appId: '1:805237617586:web:d1b5f71e48e99782702aab',
    messagingSenderId: '805237617586',
    projectId: 'untitled20-3ecfc',
    authDomain: 'untitled20-3ecfc.firebaseapp.com',
    storageBucket: 'untitled20-3ecfc.firebasestorage.app',
    measurementId: 'G-Q98NER1ETE',
  );
}
